import { ArrowRight, AudioWaveform, BadgeCheck, Bell, Boxes, Check, ChevronRight, ChevronsUpDown, CircleHelp, ClipboardList, Command, Copy, CreditCard, Eye, EyeOff, GalleryVerticalEnd, Laptop, LayoutDashboard, Loader2, LogOut, LogOut as LogOut2, Menu, MessagesSquare, MonitorCheck, MoonIcon, Palette, Plus, Search, Settings, Sparkles, SunIcon, UserCog, Users, Wrench } from "lucide-react";

export const Icons = {
    SignOut: LogOut,
    Copy,
    Check,
    Loader: Loader2,
    Eye,
    EyeOff,
    ChevronRight,
    BadgeCheck,
    Bell,
    ChevronsUpDown,
    CreditCard,
    LogOut2,
    Sparkles,
    Plus,
    Command,
    GalleryVerticalEnd,
    AudioWaveform,
    MonitorCheck,
    ClipboardList,
    CircleHelp,
    LayoutDashboard,
    MessagesSquare,
    Boxes,
    Palette,
    Settings,
    Wrench,
    UserCog,
    Users,
    Menu,
    ArrowRight,
    Laptop,
    MoonIcon,
    SunIcon,
    Search
};