import { AudioWaveform, BadgeCheck, Bell, Boxes, Check, ChevronRight, ChevronsUpDown, CircleHelp, ClipboardList, Command, Copy, CreditCard, Eye, EyeOff, GalleryVerticalEnd, LayoutDashboard, Loader2, LogOut, LogOut as LogOut2, MessagesSquare, MonitorCheck, Palette, Plus, Settings, Sparkles, UserCog, Users, Wrench } from "lucide-react";

export const Icons = {
    SignOut: LogOut,
    Copy,
    Check,
    Loader: Loader2,
    Eye,
    EyeOff,
    ChevronRight,
    BadgeCheck,
    Bell,
    ChevronsUpDown,
    CreditCard,
    LogOut2,
    Sparkles,
    Plus,
    Command,
    GalleryVerticalEnd,
    AudioWaveform,
    MonitorCheck,
    ClipboardList,
    CircleHelp,
    LayoutDashboard,
    MessagesSquare,
    Boxes,
    Palette,
    Settings,
    Wrench,
    UserCog,
    Users
};